### ISSUE TITLE
NoSuchFieldError: IMPORT_DECLARATION

### ISSUE THREAD

**Issue by HollyPony** [casser/intellij-es67#13]
Hi, I wanna try your es6/7 plugin for IntelliJ but I getting this error.

Maybe it's linked to #6 (which is the with EXPORT_DECLARATION) ?

EDIT: `Settings | Languages & Frameworks | JavaScript` is already set to ES6

My conf:

```
OSX El Capitan - V10.11.04
IntelliJ IDEA 2016.1.1
Build #IU-145.597, built on March 29, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

Have a nice day !

PS: Following the complete stack trace:

```
IMPORT_DECLARATION
java.lang.NoSuchFieldError: IMPORT_DECLARATION
    at com.intellij.lang.javascript.folding.ES7FoldingBuilder.<clinit>(ES7FoldingBuilder.java:36)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
    at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
    at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
    at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
    at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
    at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:155)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:128)
    at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:116)
    at com.intellij.lang.folding.LanguageFolding.forLanguage(LanguageFolding.java:47)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:255)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:243)
    at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:232)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.createEditorAsync(PsiAwareTextEditorProvider.java:64)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13.compute(FileEditorManagerImpl.java:857)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13.compute(FileEditorManagerImpl.java:850)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:850)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:868)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:823)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$ConfigTreeReader.process(EditorsSplitters.java:814)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters.openFiles(EditorsSplitters.java:236)
    at com.intellij.openapi.fileEditor.impl.OpenFilesActivity.runActivity(OpenFilesActivity.java:35)
    at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:149)
    at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:344)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:154)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$5.run(ProjectManagerImpl.java:387)
    at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:227)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)



java.lang.NoSuchFieldError: IMPORT_DECLARATION
    at com.intellij.lang.javascript.formatter.ES7FormattingModelBuilder.<clinit>(ES7FormattingModelBuilder.java:38)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
    at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
    at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
    at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
    at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
    at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:155)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:128)
    at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:116)
    at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:75)
    at com.intellij.lang.LanguageFormatting.forContext(LanguageFormatting.java:46)
    at com.intellij.lang.LanguageFormatting.forContext(LanguageFormatting.java:38)
    at com.intellij.psi.codeStyle.autodetect.DetectableIndentOptionsProvider.a(DetectableIndentOptionsProvider.java:83)
    at com.intellij.psi.codeStyle.autodetect.DetectableIndentOptionsProvider.getIndentOptions(DetectableIndentOptionsProvider.java:55)
    at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptionsByFile(CodeStyleSettings.java:672)
    at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptionsByFile(CodeStyleSettings.java:636)
    at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptionsByFile(CodeStyleSettings.java:631)
    at com.intellij.openapi.editor.impl.SettingsImpl.getTabSize(SettingsImpl.java:363)
    at com.intellij.openapi.editor.ex.util.EditorUtil.getTabSize(EditorUtil.java:590)
    at com.intellij.openapi.editor.impl.view.EditorView.getTabSize(EditorView.java:423)
    at com.intellij.openapi.editor.impl.view.LogicalPositionCache.reset(LogicalPositionCache.java:70)
    at com.intellij.openapi.editor.impl.view.EditorView.reinitSettings(EditorView.java:281)
    at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:566)
    at com.intellij.openapi.editor.impl.EditorFactoryImpl.a(EditorFactoryImpl.java:193)
    at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:169)
    at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.a(TextEditorComponent.java:165)
    at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.<init>(TextEditorComponent.java:100)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:62)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:55)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.createEditorComponent(PsiAwareTextEditorImpl.java:44)
    at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:46)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:38)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$1.build(PsiAwareTextEditorProvider.java:78)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$14.run(FileEditorManagerImpl.java:894)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:944)
    at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:210)
    at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:197)
    at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:649)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:354)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:230)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:183)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:372)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:468)
    at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:182)
    at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:60)
    at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:567)
    at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:601)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:372)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:359)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:338)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
    at com.sun.proxy.$Proxy43.appStarting(Unknown Source)
    at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:354)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by apottere** [comment]
+1, getting this error on the same OS/IDEA versions as above.

**Comment by smou** [comment]
+1
Windows 10
IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016

JRE: 1.8.0_112-release-b343 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

**Comment by codetony25** [comment]
+1 getting the same error, also it crashes my entire mac.

**Comment by bZichett** [comment]
Getting this error as well.  Haven't looked into exactly what feature is broken, but I've been hesitantly ignoring it with no issues cropping up.

**Comment by JongSeok-Kim** [comment]
+1 
macOs Sierra 10.12
IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016

JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by atamas101** [comment]
+1
I've got the same error
Idea 15.0.6
MacBook Pro, OS X El Capitan, 10.11.6

**Comment by andrewfinnell** [comment]
Ditto

**Comment by sharikovvladislav** [comment]
+1.
Idea 15.0.1

**Comment by LucitheR** [comment]
+1 IDEA 2016.3.1

**Comment by TonyGravagno** [comment]
+1
I have a single project with .java files and .js files. This is a Nashorn project. I just opened the project in a new window while another Java project is open in the first window ... I just didn't want to close the first Java project. On opening this Nashorn project focus was in a .java file. I double-clicked a .js file to open it and the error occurred.  HTH

IntelliJ IDEA 2016.3.1
JRE: 1.8.0_92-b14 amd64
Windows 8.1

**Comment by mylastore** [comment]
same here on Ubuntu

**Comment by imbroglioj** [comment]
Same problem. had to disable. 
Intellij IDEA 2017.1.3
openJDK: 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11
Ubuntu 16

**Comment by yanite** [comment]
+1

**Comment by maxkna111** [comment]
anyone here ??
same issue !!!

**Comment by LucitheR** [comment]
+1
