### ISSUE TITLE
Compatibility with 14.1 EAP

### ISSUE THREAD

**Issue by BastienClement** [casser/intellij-es67#2]
The latest release includes AtScript types and annotations support. Sadly, async/await is not yet supported and this plugin is not working anymore. Stacktrace:

```
TRAIT
java.lang.NoSuchFieldError: TRAIT
    at com.intellij.lang.javascript.folding.ES7FoldingBuilder.<clinit>(ES7FoldingBuilder.java:36)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
    at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
    at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
    at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
    at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:36)
    at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:127)
    at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
    at com.intellij.lang.folding.LanguageFolding.forLanguage(LanguageFolding.java:47)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.supportsDumbModeFolding(FoldingUpdate.java:240)
    at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo$1.run(DocumentFoldingInfo.java:297)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:881)
    at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.readExternal(DocumentFoldingInfo.java:283)
    at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.readFoldingState(CodeFoldingManagerImpl.java:380)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.readState(PsiAwareTextEditorProvider.java:105)
    at com.intellij.openapi.fileEditor.impl.HistoryEntry.<init>(HistoryEntry.java:79)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:856)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:829)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$ConfigTreeReader.process(EditorsSplitters.java:820)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters.openFiles(EditorsSplitters.java:244)
    at com.intellij.openapi.fileEditor.impl.OpenFilesActivity.runActivity(OpenFilesActivity.java:35)
    at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:156)
    at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:336)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:161)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$8.run(ProjectManagerImpl.java:494)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$6.run(ProgressManagerImpl.java:409)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:618)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$7.run(ProgressManagerImpl.java:421)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:193)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:282)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:232)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:180)
    at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:626)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:408)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)



java.lang.NoClassDefFoundError: Could not initialize class com.intellij.lang.javascript.folding.ES7FoldingBuilder
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
    at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
    at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
    at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
    at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:36)
    at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:127)
    at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
    at com.intellij.lang.folding.LanguageFolding.forLanguage(LanguageFolding.java:47)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.supportsDumbModeFolding(FoldingUpdate.java:240)
    at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo$1.run(DocumentFoldingInfo.java:297)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:876)
    at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.readExternal(DocumentFoldingInfo.java:283)
    at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.readFoldingState(CodeFoldingManagerImpl.java:380)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.readState(PsiAwareTextEditorProvider.java:105)
    at com.intellij.openapi.fileEditor.impl.HistoryEntry.<init>(HistoryEntry.java:79)
    at com.intellij.openapi.fileEditor.impl.EditorHistoryManager$1.run(EditorHistoryManager.java:84)
    at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:336)
    at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:328)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:191)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$8$2.run(ProjectManagerImpl.java:500)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:741)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:576)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:383)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by dcousineau** [comment]
Receiving this same issue but only when launching IDEA using JDK 1.7.0_75 on OSX instead of 1.6

**Comment by pstephenwille** [comment]
same, on Ubuntu.14.04/Java8

**Comment by casser** [comment]
This was very big change from IDEA team they now natively supporting atscript with annotations, so I need to review the main goal of this plugin.
