### ISSUE TITLE
Problem with IntelliJ Idea 13

### ISSUE THREAD

**Issue by ArthurianX** [casser/intellij-es67#4]
Hello, the plugin crashes whenever I start the IDE, this is the error: 

```com/intellij/lang/javascript/folding/ES7FoldingBuilder : Unsupported major.minor version 51.0 [Plugin: com.intellij.lang.javascript.es67]: com/intellij/lang/javascript/folding/ES7FoldingBuilder : Unsupported major.minor version 51.0 [Plugin: com.intellij.lang.javascript.es67]
com.intellij.diagnostic.PluginException: com/intellij/lang/javascript/folding/ES7FoldingBuilder : Unsupported major.minor version 51.0 [Plugin: com.intellij.lang.javascript.es67]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
    at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:45)
    at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
    at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
    at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:36)
    at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:52)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:153)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:126)
    at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:114)
    at com.intellij.lang.folding.LanguageFolding.forLanguage(LanguageFolding.java:47)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:203)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:118)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:96)
    at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.a(CodeFoldingManagerImpl.java:303)
    at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:219)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.initFolding(PsiAwareTextEditorImpl.java:49)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:806)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters.a(EditorsSplitters.java:292)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters.openFiles(EditorsSplitters.java:235)
    at com.intellij.openapi.fileEditor.impl.OpenFilesActivity$1.run(OpenFilesActivity.java:40)
    at com.intellij.openapi.fileEditor.impl.OpenFilesActivity.runActivity(OpenFilesActivity.java:45)
    at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:146)
    at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:259)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:158)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$5.run(ProjectManagerImpl.java:441)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$5.run(ProgressManagerImpl.java:269)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:471)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$6.run(ProgressManagerImpl.java:281)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
    at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:645)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
Caused by: java.lang.UnsupportedClassVersionError: com/intellij/lang/javascript/folding/ES7FoldingBuilder : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:195)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:191)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:167)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    ... 47 more

```

Is it related to Java version or what can it be ?
```

**Comment by ghost** [comment]
I have the same problem. IDEA 14.0.3 @ ubuntu 14.04; java 6

**Comment by ArthurianX** [comment]
I tried with JAVA 6,7,8 and it is exactly the same.

@casser - do you have any idea what could be causing this ?

**Comment by casser** [comment]
Guys this should be Java Version Issue, I have compiled plugin using Java 7, so if you IDE runtime is less then 7, this will cause problem, @ArthurianX which version of IDE you have and which platform ?
