### ISSUE TITLE
NoSuchFieldError on IntelliJ Ultimate 14.1.2

### ISSUE THREAD

**Issue by penguinho** [casser/intellij-es67#6]
EXPORT_DECLARATION
java.lang.NoSuchFieldError: EXPORT_DECLARATION
    at com.intellij.lang.javascript.folding.ES7FoldingBuilder.<clinit>(ES7FoldingBuilder.java:34)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
    at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
    at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
    at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
    at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
    at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:127)
    at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
    at com.intellij.lang.folding.LanguageFolding.forLanguage(LanguageFolding.java:47)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.supportsDumbModeFolding(FoldingUpdate.java:240)
    at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo$1.run(DocumentFoldingInfo.java:297)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
    at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.readExternal(DocumentFoldingInfo.java:283)
    at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.readFoldingState(CodeFoldingManagerImpl.java:382)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.readState(PsiAwareTextEditorProvider.java:107)
    at com.intellij.openapi.fileEditor.impl.HistoryEntry.<init>(HistoryEntry.java:79)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:856)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:829)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$ConfigTreeReader.process(EditorsSplitters.java:820)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters.openFiles(EditorsSplitters.java:244)
    at com.intellij.openapi.fileEditor.impl.OpenFilesActivity.runActivity(OpenFilesActivity.java:35)
    at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:156)
    at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:339)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:161)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$8.run(ProjectManagerImpl.java:490)
    at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:237)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:367)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:623)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by pixeldrew** [comment]
Same issue here (14.1.2):

EXPORT_DECLARATION
java.lang.NoSuchFieldError: EXPORT_DECLARATION
    at com.intellij.lang.javascript.folding.ES7FoldingBuilder.<clinit>(ES7FoldingBuilder.java:34)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
    at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
    at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
    at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
    at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
    at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:127)
    at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
    at com.intellij.lang.folding.LanguageFolding.forLanguage(LanguageFolding.java:47)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.supportsDumbModeFolding(FoldingUpdate.java:240)
    at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo$1.run(DocumentFoldingInfo.java:297)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
    at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.readExternal(DocumentFoldingInfo.java:283)
    at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.readFoldingState(CodeFoldingManagerImpl.java:382)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.readState(PsiAwareTextEditorProvider.java:107)
    at com.intellij.openapi.fileEditor.impl.HistoryEntry.<init>(HistoryEntry.java:79)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:856)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:829)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$ConfigTreeReader.process(EditorsSplitters.java:820)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters.openFiles(EditorsSplitters.java:244)
    at com.intellij.openapi.fileEditor.impl.OpenFilesActivity.runActivity(OpenFilesActivity.java:35)
    at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:156)
    at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:339)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:161)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$8.run(ProjectManagerImpl.java:490)
    at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:237)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:367)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:623)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by brp-nylin** [comment]
Same here.

**Comment by PillowPillow** [comment]
+1

**Comment by myhau** [comment]
+1

**Comment by Jul13nT** [comment]
+1

**Comment by tradernet** [comment]
+1

**Comment by xtreemrage** [comment]
14.1.3 same issue. I just installed it with the option to uninstall 14.1.2 silently. I have this error since 14.1.2 on a windows 7 x64 machine.

``` java
EXPORT_DECLARATION
java.lang.NoSuchFieldError: EXPORT_DECLARATION
    at com.intellij.lang.javascript.folding.ES7FoldingBuilder.<clinit>(ES7FoldingBuilder.java:34)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
    at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
    at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
    at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
    at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
    at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
    at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:127)
    at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
    at com.intellij.lang.folding.LanguageFolding.forLanguage(LanguageFolding.java:47)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.supportsDumbModeFolding(FoldingUpdate.java:240)
    at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo$1.run(DocumentFoldingInfo.java:297)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
    at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.readExternal(DocumentFoldingInfo.java:283)
    at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.readFoldingState(CodeFoldingManagerImpl.java:382)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.readState(PsiAwareTextEditorProvider.java:107)
    at com.intellij.openapi.fileEditor.impl.HistoryEntry.<init>(HistoryEntry.java:79)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:856)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:829)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters$ConfigTreeReader.process(EditorsSplitters.java:820)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters.openFiles(EditorsSplitters.java:244)
    at com.intellij.openapi.fileEditor.impl.OpenFilesActivity.runActivity(OpenFilesActivity.java:35)
    at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:156)
    at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:339)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:161)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$8.run(ProjectManagerImpl.java:490)
    at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:237)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:367)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:617)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by pixeldrew** [comment]
any word on this? interestingly I can get the plugin to work if I have multiple modules or an sdk loaded.

**Comment by thakurvivek** [comment]
Settings | Languages & Frameworks | JavaScript | Select EcmaScript 6

**Comment by clrke** [comment]
+1
